steps:
  - name: fast-build devshells
    image: bash
    commands:
      - set -e
      - nix build .#devShells.x86_64-linux.default --show-trace

  - name: fast-build packages
    image: bash
    commands:
      - set -e
      - nix-fast-build -f .#packages --no-nom

  - name: fast-build all hosts
    image: bash
    commands:
      - set -e
      - nix-fast-build -f .#colmenaHive.toplevel --no-nom

  - name: nix flake check
    image: bash
    commands:
      - nix flake check --show-trace
    when:
      - event: pull_request
      - event: push
        branch: master
