# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  tree-sitter-bash = {
    pname = "tree-sitter-bash";
    version = "49c31006d8307dcb12bc5770f35b6d5b9e2be68e";
    src = fetchFromGitHub {
      owner = "tree-sitter";
      repo = "tree-sitter-bash";
      rev = "49c31006d8307dcb12bc5770f35b6d5b9e2be68e";
      fetchSubmodules = false;
      sha256 = "sha256-JW+30zIyq8Xc7NG9V+YoFqC+57BjZXIbAvWPD2lqvIE=";
    };
    date = "2024-11-11";
  };
  tree-sitter-markdown = {
    pname = "tree-sitter-markdown";
    version = "5cdc549ab8f461aff876c5be9741027189299cec";
    src = fetchFromGitHub {
      owner = "tree-sitter-grammars";
      repo = "tree-sitter-markdown";
      rev = "5cdc549ab8f461aff876c5be9741027189299cec";
      fetchSubmodules = false;
      sha256 = "sha256-dLj233xHPCJbawUVqkxxhHXbu/CrJIHcCyLXTgsWMFo=";
    };
    date = "2024-10-21";
  };
  tree-sitter-nu = {
    pname = "tree-sitter-nu";
    version = "ef943c6f2f7bfa061aad7db7bcaca63a002f354c";
    src = fetchFromGitHub {
      owner = "LhKipp";
      repo = "tree-sitter-nu";
      rev = "ef943c6f2f7bfa061aad7db7bcaca63a002f354c";
      fetchSubmodules = false;
      sha256 = "sha256-U7IHAXo3yQgbLv7pC1/dOa/cXte+ToMc8QsDEiCMSRg=";
    };
    date = "2023-09-30";
  };
  tree-sitter-nu-new = {
    pname = "tree-sitter-nu-new";
    version = "9eedcb303de0b4e046477161fb3d2932a0146d2a";
    src = fetchFromGitHub {
      owner = "nushell";
      repo = "tree-sitter-nu";
      rev = "9eedcb303de0b4e046477161fb3d2932a0146d2a";
      fetchSubmodules = false;
      sha256 = "sha256-5Dxx+0LE34OgWWX/bEDpIH5/AZCqTVUnVTvSTX+jSy0=";
    };
    date = "2024-11-22";
  };
  tree-sitter-python = {
    pname = "tree-sitter-python";
    version = "6d14e44ea217bc5bb1c1804180e9818d7d1b8d91";
    src = fetchFromGitHub {
      owner = "tree-sitter";
      repo = "tree-sitter-python";
      rev = "6d14e44ea217bc5bb1c1804180e9818d7d1b8d91";
      fetchSubmodules = false;
      sha256 = "sha256-/jYGi2yksifMGPitlS8oM/g3YrR7RJ57imBhEyow/jc=";
    };
    date = "2024-11-11";
  };
  tree-sitter-yuck = {
    pname = "tree-sitter-yuck";
    version = "e877f6ade4b77d5ef8787075141053631ba12318";
    src = fetchFromGitHub {
      owner = "philipp-m";
      repo = "tree-sitter-yuck";
      rev = "e877f6ade4b77d5ef8787075141053631ba12318";
      fetchSubmodules = false;
      sha256 = "sha256-l8c1/7q8S78jGyl+VAVVgs8wq58PrrjycyJfWXsCgAI=";
    };
    date = "2024-05-05";
  };
}
