# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  "bookmarks.yazi" = {
    pname = "bookmarks.yazi";
    version = "fa65ba2ec762c37096a5787bd9305b62827f2753";
    src = fetchFromGitHub {
      owner = "DreamMaoMao";
      repo = "bookmarks.yazi";
      rev = "fa65ba2ec762c37096a5787bd9305b62827f2753";
      fetchSubmodules = false;
      sha256 = "sha256-0bJw2bs1o3G2LpCwUV2HPYbNtyuI6IaoA42yl26YF8s=";
    };
    date = "2025-04-22";
  };
  "fg.yazi" = {
    pname = "fg.yazi";
    version = "46a5c16f62f415f691319f984b9548249b0edc96";
    src = fetchFromGitHub {
      owner = "DreamMaoMao";
      repo = "fg.yazi";
      rev = "46a5c16f62f415f691319f984b9548249b0edc96";
      fetchSubmodules = false;
      sha256 = "sha256-B6Feg8icshHQYv04Ee/Bo9PPaiDPRyt1HwpirI/yXj8=";
    };
    date = "2025-04-22";
  };
  nu_plugin_dbus = {
    pname = "nu_plugin_dbus";
    version = "ea17d3c5fbb74a06b143ef1b929f15bbf7e505a0";
    src = fetchFromGitHub {
      owner = "devyn";
      repo = "nu_plugin_dbus";
      rev = "ea17d3c5fbb74a06b143ef1b929f15bbf7e505a0";
      fetchSubmodules = false;
      sha256 = "sha256-Ga+1zFwS/v+3iKVEz7TFmJjyBW/gq6leHeyH2vjawto=";
    };
    date = "2025-01-08";
  };
  nu_plugin_dialog = {
    pname = "nu_plugin_dialog";
    version = "850310803eb7c9a4865ac6836f519f01c62b12b5";
    src = fetchFromGitHub {
      owner = "Trivernis";
      repo = "nu-plugin-dialog";
      rev = "850310803eb7c9a4865ac6836f519f01c62b12b5";
      fetchSubmodules = false;
      sha256 = "sha256-/KWEyVqXWgJfGIgFqXIBUqzA89FB/XDzn9aciknWApM=";
    };
    date = "2024-02-03";
  };
  nu_plugin_explore = {
    pname = "nu_plugin_explore";
    version = "fa5ab698463489bfc782077915f636661712a217";
    src = fetchFromGitHub {
      owner = "amtoine";
      repo = "nu_plugin_explore";
      rev = "fa5ab698463489bfc782077915f636661712a217";
      fetchSubmodules = false;
      sha256 = "sha256-ziHjjNdLDgyrXOgFcQC34zjKX4dT7SvfS5xOrr+VeMc=";
    };
    date = "2025-03-24";
  };
  nu_plugin_file = {
    pname = "nu_plugin_file";
    version = "1ee255ddb2a773c1f683acf43c4cf3a9e195a7c5";
    src = fetchFromGitHub {
      owner = "fdncred";
      repo = "nu_plugin_file";
      rev = "1ee255ddb2a773c1f683acf43c4cf3a9e195a7c5";
      fetchSubmodules = false;
      sha256 = "sha256-ORx8BlIi7peozUBsF7N1Kq+a1c8mxp+ReloltHBtYXc=";
    };
    date = "2025-04-30";
  };
  nu_plugin_port_list = {
    pname = "nu_plugin_port_list";
    version = "f6fa5e59407d05317e7155dc9ca512ed17d12485";
    src = fetchFromGitHub {
      owner = "FMotalleb";
      repo = "nu_plugin_port_list";
      rev = "f6fa5e59407d05317e7155dc9ca512ed17d12485";
      fetchSubmodules = false;
      sha256 = "sha256-eGkUaS2MZQmowCkPB3Gow6f/MJ42b90lUpCEUeTxXfA=";
    };
    date = "2025-02-10";
  };
  nu_plugin_prometheus = {
    pname = "nu_plugin_prometheus";
    version = "4a006851e56ceb474b93fc3f2d1980304065fce4";
    src = fetchFromGitHub {
      owner = "drbrain";
      repo = "nu_plugin_prometheus";
      rev = "4a006851e56ceb474b93fc3f2d1980304065fce4";
      fetchSubmodules = false;
      sha256 = "sha256-bcAzfSaSvxOvlyJAmaxLHaPbGxhvVShawZ8mGTEABAY=";
    };
    date = "2025-05-06";
  };
  nu_plugin_skim = {
    pname = "nu_plugin_skim";
    version = "ebcdaac9f54158a26ef08f4271b8cc80626b097d";
    src = fetchFromGitHub {
      owner = "idanarye";
      repo = "nu_plugin_skim";
      rev = "ebcdaac9f54158a26ef08f4271b8cc80626b097d";
      fetchSubmodules = false;
      sha256 = "sha256-bH+llby34lqnxZXdtTEBPiw50tvvY72h+YkRRdiXXTc=";
    };
    date = "2025-04-30";
  };
  officialPluginsSource = {
    pname = "officialPluginsSource";
    version = "55bf6996ada3df4cbad331ce3be0c1090769fc7c";
    src = fetchFromGitHub {
      owner = "yazi-rs";
      repo = "plugins";
      rev = "55bf6996ada3df4cbad331ce3be0c1090769fc7c";
      fetchSubmodules = false;
      sha256 = "sha256-v/C+ZBrF1ghDt1SXpZcDELmHMVAqfr44iWxzUWynyRk=";
    };
    date = "2025-05-11";
  };
  "open-with-cmd.yazi" = {
    pname = "open-with-cmd.yazi";
    version = "433cf301c36882c31032d3280ab0c94825fc5e9f";
    src = fetchFromGitHub {
      owner = "Ape";
      repo = "open-with-cmd.yazi";
      rev = "433cf301c36882c31032d3280ab0c94825fc5e9f";
      fetchSubmodules = false;
      sha256 = "sha256-QazKfNEPFdkHwMrH4D+VMwj8fGXM8KHDdSvm1tik3dQ=";
    };
    date = "2025-02-09";
  };
  "what-size.yazi" = {
    pname = "what-size.yazi";
    version = "f1c6b691363e602d0ddbee29384017d08b608f64";
    src = fetchFromGitHub {
      owner = "pirafrank";
      repo = "what-size.yazi";
      rev = "f1c6b691363e602d0ddbee29384017d08b608f64";
      fetchSubmodules = false;
      sha256 = "sha256-M1phqmo318/VYkLWiqjEWuHlnQ+hfz5H+k8G0zsmclg=";
    };
    date = "2025-04-07";
  };
  "wl-clipboard.yazi" = {
    pname = "wl-clipboard.yazi";
    version = "c4edc4f6adf088521f11d0acf2b70610c31924f0";
    src = fetchFromGitHub {
      owner = "grappas";
      repo = "wl-clipboard.yazi";
      rev = "c4edc4f6adf088521f11d0acf2b70610c31924f0";
      fetchSubmodules = false;
      sha256 = "sha256-jlZgN93HjfK+7H27Ifk7fs0jJaIdnOyY1wKxHz1wX2c=";
    };
    date = "2025-01-05";
  };
}
