# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  "bookmarks.yazi" = {
    pname = "bookmarks.yazi";
    version = "fa65ba2ec762c37096a5787bd9305b62827f2753";
    src = fetchFromGitHub {
      owner = "DreamMaoMao";
      repo = "bookmarks.yazi";
      rev = "fa65ba2ec762c37096a5787bd9305b62827f2753";
      fetchSubmodules = false;
      sha256 = "sha256-0bJw2bs1o3G2LpCwUV2HPYbNtyuI6IaoA42yl26YF8s=";
    };
    date = "2025-04-22";
  };
  "fg.yazi" = {
    pname = "fg.yazi";
    version = "0c6ae0b52a0aa40bb468ca565c34ac413d1f93c1";
    src = fetchFromGitHub {
      owner = "DreamMaoMao";
      repo = "fg.yazi";
      rev = "0c6ae0b52a0aa40bb468ca565c34ac413d1f93c1";
      fetchSubmodules = false;
      sha256 = "sha256-pFljxXAyUfu680+MhbLrI07RcukrPXgmIvtp3f6ZVvY=";
    };
    date = "2025-07-10";
  };
  nu_plugin_dbus = {
    pname = "nu_plugin_dbus";
    version = "ea17d3c5fbb74a06b143ef1b929f15bbf7e505a0";
    src = fetchFromGitHub {
      owner = "devyn";
      repo = "nu_plugin_dbus";
      rev = "ea17d3c5fbb74a06b143ef1b929f15bbf7e505a0";
      fetchSubmodules = false;
      sha256 = "sha256-Ga+1zFwS/v+3iKVEz7TFmJjyBW/gq6leHeyH2vjawto=";
    };
    date = "2025-01-08";
  };
  nu_plugin_dialog = {
    pname = "nu_plugin_dialog";
    version = "850310803eb7c9a4865ac6836f519f01c62b12b5";
    src = fetchFromGitHub {
      owner = "Trivernis";
      repo = "nu-plugin-dialog";
      rev = "850310803eb7c9a4865ac6836f519f01c62b12b5";
      fetchSubmodules = false;
      sha256 = "sha256-/KWEyVqXWgJfGIgFqXIBUqzA89FB/XDzn9aciknWApM=";
    };
    date = "2024-02-03";
  };
  nu_plugin_explore = {
    pname = "nu_plugin_explore";
    version = "fa5ab698463489bfc782077915f636661712a217";
    src = fetchFromGitHub {
      owner = "amtoine";
      repo = "nu_plugin_explore";
      rev = "fa5ab698463489bfc782077915f636661712a217";
      fetchSubmodules = false;
      sha256 = "sha256-ziHjjNdLDgyrXOgFcQC34zjKX4dT7SvfS5xOrr+VeMc=";
    };
    date = "2025-03-24";
  };
  nu_plugin_file = {
    pname = "nu_plugin_file";
    version = "ee1157c3f8f0e7b326bb0477f20d98b3d98759b9";
    src = fetchFromGitHub {
      owner = "fdncred";
      repo = "nu_plugin_file";
      rev = "ee1157c3f8f0e7b326bb0477f20d98b3d98759b9";
      fetchSubmodules = false;
      sha256 = "sha256-n/E7CpRLZvg+NWI+n3VzE+qrTKrpBbFNfSsHZEqRNiU=";
    };
    date = "2025-06-17";
  };
  nu_plugin_port_list = {
    pname = "nu_plugin_port_list";
    version = "f6fa5e59407d05317e7155dc9ca512ed17d12485";
    src = fetchFromGitHub {
      owner = "FMotalleb";
      repo = "nu_plugin_port_list";
      rev = "f6fa5e59407d05317e7155dc9ca512ed17d12485";
      fetchSubmodules = false;
      sha256 = "sha256-eGkUaS2MZQmowCkPB3Gow6f/MJ42b90lUpCEUeTxXfA=";
    };
    date = "2025-02-10";
  };
  nu_plugin_prometheus = {
    pname = "nu_plugin_prometheus";
    version = "4a006851e56ceb474b93fc3f2d1980304065fce4";
    src = fetchFromGitHub {
      owner = "drbrain";
      repo = "nu_plugin_prometheus";
      rev = "4a006851e56ceb474b93fc3f2d1980304065fce4";
      fetchSubmodules = false;
      sha256 = "sha256-bcAzfSaSvxOvlyJAmaxLHaPbGxhvVShawZ8mGTEABAY=";
    };
    date = "2025-05-06";
  };
  nu_plugin_skim = {
    pname = "nu_plugin_skim";
    version = "613d520df8fc3a493cdc5284c68c4031263f0eea";
    src = fetchFromGitHub {
      owner = "idanarye";
      repo = "nu_plugin_skim";
      rev = "613d520df8fc3a493cdc5284c68c4031263f0eea";
      fetchSubmodules = false;
      sha256 = "sha256-8gO6pT40zBlFxPRapIO9qpMI9whutttqYgOPr91B9Ec=";
    };
    date = "2025-06-11";
  };
  officialPluginsSource = {
    pname = "officialPluginsSource";
    version = "1ab21d43c7c6d326c1b9b06610ce7c8686257c43";
    src = fetchFromGitHub {
      owner = "yazi-rs";
      repo = "plugins";
      rev = "1ab21d43c7c6d326c1b9b06610ce7c8686257c43";
      fetchSubmodules = false;
      sha256 = "sha256-4p+VXUr76kC/dyJZzzkCwNGEUV53YYZ3tYoFpsKboU0=";
    };
    date = "2025-07-20";
  };
  "open-with-cmd.yazi" = {
    pname = "open-with-cmd.yazi";
    version = "433cf301c36882c31032d3280ab0c94825fc5e9f";
    src = fetchFromGitHub {
      owner = "Ape";
      repo = "open-with-cmd.yazi";
      rev = "433cf301c36882c31032d3280ab0c94825fc5e9f";
      fetchSubmodules = false;
      sha256 = "sha256-QazKfNEPFdkHwMrH4D+VMwj8fGXM8KHDdSvm1tik3dQ=";
    };
    date = "2025-02-09";
  };
  "what-size.yazi" = {
    pname = "what-size.yazi";
    version = "d8966568f2a80394bf1f9a1ace6708ddd4cc8154";
    src = fetchFromGitHub {
      owner = "pirafrank";
      repo = "what-size.yazi";
      rev = "d8966568f2a80394bf1f9a1ace6708ddd4cc8154";
      fetchSubmodules = false;
      sha256 = "sha256-s2BifzWr/uewDI6Bowy7J+5LrID6I6OFEA5BrlOPNcM=";
    };
    date = "2025-06-19";
  };
  "wl-clipboard.yazi" = {
    pname = "wl-clipboard.yazi";
    version = "c4edc4f6adf088521f11d0acf2b70610c31924f0";
    src = fetchFromGitHub {
      owner = "grappas";
      repo = "wl-clipboard.yazi";
      rev = "c4edc4f6adf088521f11d0acf2b70610c31924f0";
      fetchSubmodules = false;
      sha256 = "sha256-jlZgN93HjfK+7H27Ifk7fs0jJaIdnOyY1wKxHz1wX2c=";
    };
    date = "2025-01-05";
  };
}
