# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  "bookmarks.yazi" = {
    pname = "bookmarks.yazi";
    version = "fa65ba2ec762c37096a5787bd9305b62827f2753";
    src = fetchFromGitHub {
      owner = "DreamMaoMao";
      repo = "bookmarks.yazi";
      rev = "fa65ba2ec762c37096a5787bd9305b62827f2753";
      fetchSubmodules = false;
      sha256 = "sha256-0bJw2bs1o3G2LpCwUV2HPYbNtyuI6IaoA42yl26YF8s=";
    };
    date = "2025-04-22";
  };
  "fg.yazi" = {
    pname = "fg.yazi";
    version = "c201a3e1c0cda921c06019127886f16faef4b17e";
    src = fetchFromGitHub {
      owner = "DreamMaoMao";
      repo = "fg.yazi";
      rev = "c201a3e1c0cda921c06019127886f16faef4b17e";
      fetchSubmodules = false;
      sha256 = "sha256-PNZngyiWuzw2bmJ4v66er9HEAcD5z0Dr6iKYwcxJwf0=";
    };
    date = "2025-07-27";
  };
  "gvfs.yazi" = {
    pname = "gvfs.yazi";
    version = "0927f5f2a6df2bb137d8892e81d81e1a6b166073";
    src = fetchFromGitHub {
      owner = "boydaihungst";
      repo = "gvfs.yazi";
      rev = "0927f5f2a6df2bb137d8892e81d81e1a6b166073";
      fetchSubmodules = false;
      sha256 = "sha256-Le5NE5jwd+GAD538pgEfVYDM2s380cUCyKIiBf7p7zk=";
    };
    date = "2025-08-08";
  };
  nu_plugin_dbus = {
    pname = "nu_plugin_dbus";
    version = "ea17d3c5fbb74a06b143ef1b929f15bbf7e505a0";
    src = fetchFromGitHub {
      owner = "devyn";
      repo = "nu_plugin_dbus";
      rev = "ea17d3c5fbb74a06b143ef1b929f15bbf7e505a0";
      fetchSubmodules = false;
      sha256 = "sha256-Ga+1zFwS/v+3iKVEz7TFmJjyBW/gq6leHeyH2vjawto=";
    };
    date = "2025-01-08";
  };
  nu_plugin_dialog = {
    pname = "nu_plugin_dialog";
    version = "850310803eb7c9a4865ac6836f519f01c62b12b5";
    src = fetchFromGitHub {
      owner = "Trivernis";
      repo = "nu-plugin-dialog";
      rev = "850310803eb7c9a4865ac6836f519f01c62b12b5";
      fetchSubmodules = false;
      sha256 = "sha256-/KWEyVqXWgJfGIgFqXIBUqzA89FB/XDzn9aciknWApM=";
    };
    date = "2024-02-03";
  };
  nu_plugin_explore = {
    pname = "nu_plugin_explore";
    version = "fa5ab698463489bfc782077915f636661712a217";
    src = fetchFromGitHub {
      owner = "amtoine";
      repo = "nu_plugin_explore";
      rev = "fa5ab698463489bfc782077915f636661712a217";
      fetchSubmodules = false;
      sha256 = "sha256-ziHjjNdLDgyrXOgFcQC34zjKX4dT7SvfS5xOrr+VeMc=";
    };
    date = "2025-03-24";
  };
  nu_plugin_file = {
    pname = "nu_plugin_file";
    version = "9331b9b163e5f14eb4142e1b088bb69601fff3cf";
    src = fetchFromGitHub {
      owner = "fdncred";
      repo = "nu_plugin_file";
      rev = "9331b9b163e5f14eb4142e1b088bb69601fff3cf";
      fetchSubmodules = false;
      sha256 = "sha256-GyZlyEiOlL745fjMVPLEHwQGCFPq3LEhI9dezRp2PRc=";
    };
    date = "2025-07-24";
  };
  nu_plugin_port_list = {
    pname = "nu_plugin_port_list";
    version = "f6fa5e59407d05317e7155dc9ca512ed17d12485";
    src = fetchFromGitHub {
      owner = "FMotalleb";
      repo = "nu_plugin_port_list";
      rev = "f6fa5e59407d05317e7155dc9ca512ed17d12485";
      fetchSubmodules = false;
      sha256 = "sha256-eGkUaS2MZQmowCkPB3Gow6f/MJ42b90lUpCEUeTxXfA=";
    };
    date = "2025-02-10";
  };
  nu_plugin_prometheus = {
    pname = "nu_plugin_prometheus";
    version = "4a006851e56ceb474b93fc3f2d1980304065fce4";
    src = fetchFromGitHub {
      owner = "drbrain";
      repo = "nu_plugin_prometheus";
      rev = "4a006851e56ceb474b93fc3f2d1980304065fce4";
      fetchSubmodules = false;
      sha256 = "sha256-bcAzfSaSvxOvlyJAmaxLHaPbGxhvVShawZ8mGTEABAY=";
    };
    date = "2025-05-06";
  };
  nu_plugin_skim = {
    pname = "nu_plugin_skim";
    version = "d04657f48ea8b2bde120daadae6a4177802772c0";
    src = fetchFromGitHub {
      owner = "idanarye";
      repo = "nu_plugin_skim";
      rev = "d04657f48ea8b2bde120daadae6a4177802772c0";
      fetchSubmodules = false;
      sha256 = "sha256-bTVO5qLaxdSbgy0ybQJhUYa3imQSP5I6Vlban1qJeJg=";
    };
    date = "2025-07-27";
  };
  officialPluginsSource = {
    pname = "officialPluginsSource";
    version = "de53d90cb2740f84ae595f93d0c4c23f8618a9e4";
    src = fetchFromGitHub {
      owner = "yazi-rs";
      repo = "plugins";
      rev = "de53d90cb2740f84ae595f93d0c4c23f8618a9e4";
      fetchSubmodules = false;
      sha256 = "sha256-ixZKOtLOwLHLeSoEkk07TB3N57DXoVEyImR3qzGUzxQ=";
    };
    date = "2025-07-23";
  };
  "open-with-cmd.yazi" = {
    pname = "open-with-cmd.yazi";
    version = "433cf301c36882c31032d3280ab0c94825fc5e9f";
    src = fetchFromGitHub {
      owner = "Ape";
      repo = "open-with-cmd.yazi";
      rev = "433cf301c36882c31032d3280ab0c94825fc5e9f";
      fetchSubmodules = false;
      sha256 = "sha256-QazKfNEPFdkHwMrH4D+VMwj8fGXM8KHDdSvm1tik3dQ=";
    };
    date = "2025-02-09";
  };
  "searchjump.yazi" = {
    pname = "searchjump.yazi";
    version = "7fafec3e667f2b93d3ad21989ef75bbf95bb43fc";
    src = fetchFromGitHub {
      owner = "DreamMaoMao";
      repo = "searchjump.yazi";
      rev = "7fafec3e667f2b93d3ad21989ef75bbf95bb43fc";
      fetchSubmodules = false;
      sha256 = "sha256-zH/X7YUpfDiOcEKuXG4J1MZFj3Dv28rWOi9XEod8NNo=";
    };
    date = "2025-07-11";
  };
  "what-size.yazi" = {
    pname = "what-size.yazi";
    version = "d8966568f2a80394bf1f9a1ace6708ddd4cc8154";
    src = fetchFromGitHub {
      owner = "pirafrank";
      repo = "what-size.yazi";
      rev = "d8966568f2a80394bf1f9a1ace6708ddd4cc8154";
      fetchSubmodules = false;
      sha256 = "sha256-s2BifzWr/uewDI6Bowy7J+5LrID6I6OFEA5BrlOPNcM=";
    };
    date = "2025-06-19";
  };
  "whoosh.yazi" = {
    pname = "whoosh.yazi";
    version = "49dd9663df874e1fc662b9172831121ae81657f2";
    src = fetchFromGitHub {
      owner = "WhoSowSee";
      repo = "whoosh.yazi";
      rev = "49dd9663df874e1fc662b9172831121ae81657f2";
      fetchSubmodules = false;
      sha256 = "sha256-n3FKWaTFgABwB31efK+D6Javty5dLe+ju8HA8fd2uWo=";
    };
    date = "2025-08-04";
  };
  "wl-clipboard.yazi" = {
    pname = "wl-clipboard.yazi";
    version = "c4edc4f6adf088521f11d0acf2b70610c31924f0";
    src = fetchFromGitHub {
      owner = "grappas";
      repo = "wl-clipboard.yazi";
      rev = "c4edc4f6adf088521f11d0acf2b70610c31924f0";
      fetchSubmodules = false;
      sha256 = "sha256-jlZgN93HjfK+7H27Ifk7fs0jJaIdnOyY1wKxHz1wX2c=";
    };
    date = "2025-01-05";
  };
}
