# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  tree-sitter-bash = {
    pname = "tree-sitter-bash";
    version = "56b54c61fb48bce0c63e3dfa2240b5d274384763";
    src = fetchFromGitHub {
      owner = "tree-sitter";
      repo = "tree-sitter-bash";
      rev = "56b54c61fb48bce0c63e3dfa2240b5d274384763";
      fetchSubmodules = false;
      sha256 = "sha256-vRaN/mNfpR+hdv2HVS1bzaW0o+HGjizRFsk3iinICJE=";
    };
    date = "2025-06-04";
  };
  tree-sitter-javascript = {
    pname = "tree-sitter-javascript";
    version = "6fbef40512dcd9f0a61ce03a4c9ae7597b36ab5c";
    src = fetchFromGitHub {
      owner = "tree-sitter";
      repo = "tree-sitter-javascript";
      rev = "6fbef40512dcd9f0a61ce03a4c9ae7597b36ab5c";
      fetchSubmodules = false;
      sha256 = "sha256-X9DDCBF+gQYL0syfqgKVFvzoy2tnBl+veaYi7bUuRms=";
    };
    date = "2025-01-30";
  };
  tree-sitter-markdown = {
    pname = "tree-sitter-markdown";
    version = "7462bb66ac7e90312082269007fac2772fe5efd1";
    src = fetchFromGitHub {
      owner = "tree-sitter-grammars";
      repo = "tree-sitter-markdown";
      rev = "7462bb66ac7e90312082269007fac2772fe5efd1";
      fetchSubmodules = false;
      sha256 = "sha256-TvGTKsna1NS31/Tp9gBpndG1hNCRCEErBq1DK3pQHkU=";
    };
    date = "2025-06-17";
  };
  tree-sitter-nu = {
    pname = "tree-sitter-nu";
    version = "6544c4383643cf8608d50def2247a7af8314e148";
    src = fetchFromGitHub {
      owner = "nushell";
      repo = "tree-sitter-nu";
      rev = "6544c4383643cf8608d50def2247a7af8314e148";
      fetchSubmodules = false;
      sha256 = "sha256-+KsRkfx0WmcfYBP7zxXqL8kPm/HsBjuI56/v910kMFU=";
    };
    date = "2025-07-15";
  };
  tree-sitter-python = {
    pname = "tree-sitter-python";
    version = "710796b8b877a970297106e5bbc8e2afa47f86ec";
    src = fetchFromGitHub {
      owner = "tree-sitter";
      repo = "tree-sitter-python";
      rev = "710796b8b877a970297106e5bbc8e2afa47f86ec";
      fetchSubmodules = false;
      sha256 = "sha256-t9etfZcrliF7f9hfiomh2U9P+3ufAm8iSK1y9rOhP7s=";
    };
    date = "2025-01-30";
  };
  tree-sitter-yuck = {
    pname = "tree-sitter-yuck";
    version = "e877f6ade4b77d5ef8787075141053631ba12318";
    src = fetchFromGitHub {
      owner = "philipp-m";
      repo = "tree-sitter-yuck";
      rev = "e877f6ade4b77d5ef8787075141053631ba12318";
      fetchSubmodules = false;
      sha256 = "sha256-l8c1/7q8S78jGyl+VAVVgs8wq58PrrjycyJfWXsCgAI=";
    };
    date = "2024-05-05";
  };
}
