# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  tree-sitter-bash = {
    pname = "tree-sitter-bash";
    version = "a06c2e4415e9bc0346c6b86d401879ffb44058f7";
    src = fetchFromGitHub {
      owner = "tree-sitter";
      repo = "tree-sitter-bash";
      rev = "a06c2e4415e9bc0346c6b86d401879ffb44058f7";
      fetchSubmodules = false;
      sha256 = "sha256-ONQ1Ljk3aRWjElSWD2crCFZraZoRj3b3/VELz1789GE=";
    };
    date = "2025-12-02";
  };
  tree-sitter-javascript = {
    pname = "tree-sitter-javascript";
    version = "58404d8cf191d69f2674a8fd507bd5776f46cb11";
    src = fetchFromGitHub {
      owner = "tree-sitter";
      repo = "tree-sitter-javascript";
      rev = "58404d8cf191d69f2674a8fd507bd5776f46cb11";
      fetchSubmodules = false;
      sha256 = "sha256-+fbTNX7qz6Ew1NrXF49wQh3RVl2ZQ3R7YXMkclUoNT8=";
    };
    date = "2025-09-14";
  };
  tree-sitter-markdown = {
    pname = "tree-sitter-markdown";
    version = "c3570720f7f7bbad22fe96603f106276618e0cf5";
    src = fetchFromGitHub {
      owner = "tree-sitter-grammars";
      repo = "tree-sitter-markdown";
      rev = "c3570720f7f7bbad22fe96603f106276618e0cf5";
      fetchSubmodules = false;
      sha256 = "sha256-wQKcqU0V6gHj84qOkUwdXsBW3f6MNfJMFxuGTucAgh8=";
    };
    date = "2026-05-06";
  };
  tree-sitter-nu = {
    pname = "tree-sitter-nu";
    version = "348b787d8b0409091d85fe9d4eb007fe9f3406bb";
    src = fetchFromGitHub {
      owner = "nushell";
      repo = "tree-sitter-nu";
      rev = "348b787d8b0409091d85fe9d4eb007fe9f3406bb";
      fetchSubmodules = false;
      sha256 = "sha256-OL3fqHjimJ9VrR2UoeIdLxKKcsA1J80A9T8GSBO9KwE=";
    };
    date = "2026-04-22";
  };
  tree-sitter-python = {
    pname = "tree-sitter-python";
    version = "26855eabccb19c6abf499fbc5b8dc7cc9ab8bc64";
    src = fetchFromGitHub {
      owner = "tree-sitter";
      repo = "tree-sitter-python";
      rev = "26855eabccb19c6abf499fbc5b8dc7cc9ab8bc64";
      fetchSubmodules = false;
      sha256 = "sha256-gHeja/X/Ux8fa5rh0b69/bcUcmHBcXsK5uJ1ibtuI20=";
    };
    date = "2025-09-15";
  };
  tree-sitter-yuck = {
    pname = "tree-sitter-yuck";
    version = "6c60112b3b3e739fb1ca4a8ea4bea2b6ffe11318";
    src = fetchFromGitHub {
      owner = "philipp-m";
      repo = "tree-sitter-yuck";
      rev = "6c60112b3b3e739fb1ca4a8ea4bea2b6ffe11318";
      fetchSubmodules = false;
      sha256 = "sha256-ZbUN9lv2nGgpQ0rU+H38gSCdCSav//47ESHXDMuQX7c=";
    };
    date = "2026-04-03";
  };
}
