# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  tree-sitter-bash = {
    pname = "tree-sitter-bash";
    version = "b930fed16910a74c230e09ea5b97f671448d2116";
    src = fetchFromGitHub {
      owner = "tree-sitter";
      repo = "tree-sitter-bash";
      rev = "b930fed16910a74c230e09ea5b97f671448d2116";
      fetchSubmodules = false;
      sha256 = "sha256-7VZRkoQc6l+YWzdsnXM6FlTzJq/eCgH1/SWkh6WTjp8=";
    };
    date = "2025-08-28";
  };
  tree-sitter-javascript = {
    pname = "tree-sitter-javascript";
    version = "44c892e0be055ac465d5eeddae6d3e194424e7de";
    src = fetchFromGitHub {
      owner = "tree-sitter";
      repo = "tree-sitter-javascript";
      rev = "44c892e0be055ac465d5eeddae6d3e194424e7de";
      fetchSubmodules = false;
      sha256 = "sha256-2Jj/SUG+k8lHlGSuPZvHjJojvQFgDiZHZzH8xLu7suE=";
    };
    date = "2025-09-01";
  };
  tree-sitter-markdown = {
    pname = "tree-sitter-markdown";
    version = "7462bb66ac7e90312082269007fac2772fe5efd1";
    src = fetchFromGitHub {
      owner = "tree-sitter-grammars";
      repo = "tree-sitter-markdown";
      rev = "7462bb66ac7e90312082269007fac2772fe5efd1";
      fetchSubmodules = false;
      sha256 = "sha256-TvGTKsna1NS31/Tp9gBpndG1hNCRCEErBq1DK3pQHkU=";
    };
    date = "2025-06-17";
  };
  tree-sitter-nu = {
    pname = "tree-sitter-nu";
    version = "cc4624fbc6ec3563d98fbe8f215a8b8e10b16f32";
    src = fetchFromGitHub {
      owner = "nushell";
      repo = "tree-sitter-nu";
      rev = "cc4624fbc6ec3563d98fbe8f215a8b8e10b16f32";
      fetchSubmodules = false;
      sha256 = "sha256-cQiUrsSIs7AgDifOChKScZj+/25qUxEVMg3TcsGkQUY=";
    };
    date = "2025-08-23";
  };
  tree-sitter-python = {
    pname = "tree-sitter-python";
    version = "710796b8b877a970297106e5bbc8e2afa47f86ec";
    src = fetchFromGitHub {
      owner = "tree-sitter";
      repo = "tree-sitter-python";
      rev = "710796b8b877a970297106e5bbc8e2afa47f86ec";
      fetchSubmodules = false;
      sha256 = "sha256-t9etfZcrliF7f9hfiomh2U9P+3ufAm8iSK1y9rOhP7s=";
    };
    date = "2025-01-30";
  };
  tree-sitter-yuck = {
    pname = "tree-sitter-yuck";
    version = "e877f6ade4b77d5ef8787075141053631ba12318";
    src = fetchFromGitHub {
      owner = "philipp-m";
      repo = "tree-sitter-yuck";
      rev = "e877f6ade4b77d5ef8787075141053631ba12318";
      fetchSubmodules = false;
      sha256 = "sha256-l8c1/7q8S78jGyl+VAVVgs8wq58PrrjycyJfWXsCgAI=";
    };
    date = "2024-05-05";
  };
}
