## Nushell Plugins
# ToDo:
# - https://codeberg.org/Taywee/nu-plugin-bexpand
[nu_plugin_explore]
src.git = "https://github.com/amtoine/nu_plugin_explore"
# src.git = "https://github.com/kraftnix/nu_plugin_explore"
# src.branch = "bump-0_100_0"
fetch.github = "amtoine/nu_plugin_explore"
# fetch.github = "kraftnix/nu_plugin_explore"

[nu_plugin_dbus]
src.git = "https://github.com/devyn/nu_plugin_dbus"
fetch.github = "devyn/nu_plugin_dbus"

[nu_plugin_dialog]
src.git = "https://github.com/Trivernis/nu-plugin-dialog"
fetch.github = "Trivernis/nu-plugin-dialog"

[nu_plugin_file]
src.git = "https://github.com/fdncred/nu_plugin_file"
fetch.github = "fdncred/nu_plugin_file"

[nu_plugin_port_list]
src.git = "https://github.com/FMotalleb/nu_plugin_port_list"
fetch.github = "FMotalleb/nu_plugin_port_list"

[nu_plugin_prometheus]
src.git = "https://github.com/drbrain/nu_plugin_prometheus"
fetch.github = "drbrain/nu_plugin_prometheus"

[nu_plugin_skim]
# src.git = "https://github.com/idanarye/nu_plugin_skim"
src.github = "idanarye/nu_plugin_skim"
fetch.github = "idanarye/nu_plugin_skim"
