# TreeSitter
[tree-sitter-nu]
src.git = "https://github.com/nushell/tree-sitter-nu" # track master
fetch.github = "nushell/tree-sitter-nu"

[tree-sitter-bash]
src.git = "https://github.com/tree-sitter/tree-sitter-bash"
fetch.github = "tree-sitter/tree-sitter-bash"

[tree-sitter-markdown]
src.git = "https://github.com/tree-sitter-grammars/tree-sitter-markdown"
fetch.github = "tree-sitter-grammars/tree-sitter-markdown"

[tree-sitter-javascript]
src.git = "https://github.com/tree-sitter/tree-sitter-javascript"
fetch.github = "tree-sitter/tree-sitter-javascript"

[tree-sitter-python]
src.git = "https://github.com/tree-sitter/tree-sitter-python"
fetch.github = "tree-sitter/tree-sitter-python"

[tree-sitter-yuck]
src.git = "https://github.com/philipp-m/tree-sitter-yuck"
fetch.github = "philipp-m/tree-sitter-yuck"
